package com.behnamdev.features.crypto.domain.service

import com.behnamdev.features.crypto.domain.repository.CryptoRepository
import com.behnamdev.features.crypto.domain.model.CryptoItem

class GetCryptoListUseCase(private val repository: CryptoRepository) {

    // دیکشنری نگاشت نمادهای اختصاری به نام کامل ارزهای دیجیتال
    private val cryptoNamesMap = mapOf(
        "BTC" to "Bitcoin",
        "ETH" to "Ethereum",
        "LTC" to "Litecoin",
        "BNB" to "BNB",
        "NEO" to "NEO",
        "GAS" to "Gas",
        "LRC" to "Loopring",
        "QTUM" to "Qtum",
        "ZRX" to "0x",
        "KNC" to "Kyber Network Crystal",
        "FUN" to "FUNToken",
        "ZKC" to "ZkCrypto",
        "IOTA" to "IOTA",
        "CHAINLINK" to "Chainlink",
        "XVG" to "Verge",
        "MTL" to "Metal DAO",
        "ETC" to "Ethereum Classic",
        "ZEC" to "Zcash",
        "BNT" to "Bancor",
        "DASH" to "Dash",
        "REQ" to "Request",
        "TRX" to "TRON",
        "POWR" to "Powerledger",
        "ARK" to "Ark",
        "XRP" to "XRP",
        "ENJ" to "Enjin Coin",
        "STORJ" to "Storj",
        "BAT" to "Basic Attention Token",
        "LSK" to "Lisk",
        "MANA" to "Decentraland",
        "ADX" to "AdEx",
        "ADA" to "Cardano",
        "XLM" to "Stellar",
        "AVNT" to "Aventus",
        "ICX" to "ICON",
        "RLC" to "iExec RLC",
        "PIVX" to "PIVX",
        "IOST" to "IOST",
        "STEEM" to "Steem",
        "ZIL" to "Zilliqa",
        "ONT" to "Ontology",
        "WAN" to "Wanchain",
        "PUMP" to "PumpCoin",
        "SYS" to "Syscoin",
        "TUSD" to "TrueUSD",
        "ZEN" to "Horizen",
        "CVC" to "Civic",
        "THETA" to "Theta Network",
        "IOTX" to "IoTeX",
        "QKC" to "QuarkChain",
        "SC" to "Siacoin",
        "ARDR" to "Ardor",
        "VET" to "VeChain",
        "SENT" to "Sentinel",
        "RLUSD" to "Ripple USD",
        "FOGO" to "Fogo Labs",
        "RVN" to "Ravencoin",
        "DCR" to "Decred",
        "FRAX" to "Frax",
        "U" to "U.Network",
        "USDC" to "USDC",
        "ONG" to "Ontology Gas",
        "FET" to "Artificial Superintelligence Alliance",
        "CELR" to "Celer Network",
        "ATOM" to "Cosmos",
        "PHB" to "Phoenix",
        "TFUEL" to "Theta Fuel",
        "ONE" to "Harmony",
        "ZKP" to "ZKPass",
        "ALGO" to "Algorand",
        "DOGE" to "Dogecoin",
        "DUSK" to "Dusk",
        "ANKR" to "Ankr",
        "币安人生" to "Binance Life",
        "COS" to "Contentos",
        "CHZ" to "Chiliz",
        "BAND" to "Band Protocol",
        "XTZ" to "Tezos",
        "HBAR" to "Hedera",
        "NKN" to "NKN",
        "HOLO" to "Holo",
        "KAVA" to "Kava",
        "STX" to "Stacks",
        "ARPA" to "ARPA Network",
        "BCH" to "Bitcoin Cash",
        "LINEA" to "Linea",
        "FTT" to "FTX Token",
        "USDE" to "USDe",
        "EUR" to "Euro",
        "OGN" to "Origin Protocol",
        "MBL" to "MovieBloc",
        "COTI" to "COTI",
        "OPEN" to "Open Governance Token",
        "SOL" to "Solana",
        "BREV" to "Brevity",
        "CTSI" to "Cartesi",
        "HIVE" to "Hive",
        "CHR" to "Chromia",
        "SOMI" to "Somi Network",
        "WLFI" to "World Liberty Financial",
        "MDT" to "Measurable Data Token",
        "DGB" to "DigiByte",
        "MITO" to "Mito Finance",
        "COMP" to "Compound",
        "DOLO" to "Dolo Coin",
        "SNX" to "Synthetix",
        "KGST" to "Kingstoken",
        "RUNE" to "THORChain",
        "FIO" to "FIO Protocol",
        "AVA" to "AVA",
        "YFI" to "yearn.finance",
        "JST" to "JUST",
        "SAND" to "The Sandbox",
        "CRV" to "Curve DAO Token",
        "NMR" to "Numeraire",
        "DOT" to "Polkadot",
        "LUNA" to "Terra Classic",
        "IDEX" to "IDEX",
        "RSR" to "Reserve Rights",
        "PAXG" to "PAX Gold",
        "TRB" to "Tellor",
        "AT" to "ABCC Token",
        "W" to "Wormhole",
        "PLUME" to "Plume Network",
        "SUSHI" to "SushiSwap",
        "KSM" to "Kusama",
        "DIA" to "DIA",
        "EGLD" to "MultiversX",
        "UMA" to "UMA",
        "BEL" to "Bella Protocol",
        "UNI" to "Uniswap",
        "OXT" to "Orchid",
        "SUN" to "SUN",
        "AVAX" to "Avalanche",
        "SCRT" to "Secret",
        "XVS" to "Venus",
        "NEAR" to "NEAR Protocol",
        "AAVE" to "Aave",
        "FIL" to "Filecoin",
        "INJ" to "Injective",
        "AUDIO" to "Audius",
        "CTK" to "Coreum",
        "MET" to "Metronome",
        "AXS" to "Axie Infinity",
        "BANK" to "Float Protocol",
        "STRAX" to "Stratis",
        "ROSE" to "Oasis Network",
        "SKL" to "SKALE",
        "ALLO" to "Allo Network",
        "GLM" to "Golem",
        "GRT" to "The Graph",
        "JUV" to "Juventus Fan Token",
        "PSG" to "Paris Saint-Germain Fan Token",
        "1INCH" to "1inch Network",
        "SAPIEN" to "Sapien",
        "OG" to "OG Fan Token",
        "ATM" to "Atlético de Madrid Fan Token",
        "ASR" to "AS Roma Fan Token",
        "CELO" to "Celo"
    )

    suspend fun execute(): List<CryptoItem> {
        val remoteList = repository.fetchRemoteCrypto()

        // مپ کردن لیست و جایگذاری مقدار فیلد name بر اساس symbol
        return remoteList.map { item ->
            val fullName = cryptoNamesMap[item.symbol.uppercase()] ?: item.symbol
            // کپی کردن مدل با نام جدید (با فرض اینکه دیتا کلاس شما متد copy دارد)
            item.copy(name = fullName)
        }
    }
}